# Verbose
/control/verbose 0
/run/verbose 0
/process/verbose 0
/particle/verbose 0
/geometry/navigator/verbose 0
/event/verbose 0
/tracking/verbose 0

# Visual
/vis/scene/add/hits
/vis/scene/add/axes 0 0 0 10 m
/vis/open HepRepFile
/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi 180 90 deg
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/scene/endOfEventAction accumulate
/vis/reviewKeptEvents

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set N12 blue
/vis/modeling/trajectories/drawByParticleID-0/set C11 red
/vis/modeling/trajectories/drawByParticleID-0/set Pb208 orange
/vis/modeling/trajectories/drawByParticleID-0/set deuteron orange

# Turn On/Off the magnetic field
/det/field 0

# Define the target material
#/det/target/material G4_LITHIUM_FLUORIDE
#/det/target/material G4_POLYETHYLENE
#/det/target/target_material G4_Pb
#G4_POLYETHYLENE
#/det/target/width 1.e-6
/det/target/Z 18
/det/target/A 40


# Define target position (x, y, z)(cm)
#/det/target/pos 0. 0. 148.
/det/target/pos 0. 0. 0.

# Define the primary particle
/det/primary/energy 50.0 MeV
/det/primary/Z 2
/det/primary/A 6
/det/primary/pos 0. 0. -150.
#/det/primary/pos 0. 0. 148.



############################################
### Recoil must be the lighest particle! ###
############################################

# Define the recoil particle
/det/recoil/A 40
/det/recoil/Z 18

# Define the ejectile particle
/det/ejectile/A 6
/det/ejectile/Z 2
/det/ejectile/Ex 0.0 MeV

## Define decay particle 1
#/det/decayp1/A 1
#/det/decayp1/Z 1

## Define decay particle
#/det/decayp2/A 11
#/det/decayp2/Z 6

#/vis/disable

# Set current
/det/currentValue 32.8
#/det/currentValue {corriente}
/det/currentValue2 0.0

##Set external Xsection
/det/xsec/ext_xsec 1
#/det/xsec/filename xsections/bu_8b_208pb.dat
/det/xsec/filename xsections/elast_12n_208pb.dat

# This this command updates the geometry with all the inputs above
#/det/update

/run/beamOn 10
#/run/beamOn 10000000
